Refactored

diff --git a/tmux/.tmux/wifi b/tmux/.tmux/wifi
--- a/tmux/.tmux/wifi
+++ b/tmux/.tmux/wifi
@@ -56,8 +56,8 @@ airport_path="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Cu
 
 # Check if airport is available
 if [[ ! -x $airport_path ]]; then
-    echo "$airport_path: not found" 1>&2
-    exit 1
+  echo "$airport_path: not found" 1>&2
+  exit 1
 fi
 
 # The Unicode Block Elements
@@ -86,8 +86,8 @@ signals=(▂ ▅ ▇)
 # Get the wifi information and then set it to an info array
 info=( $(eval "$airport_path" --getinfo | grep -E "^ *(agrCtlRSSI|state|lastTxRate|SSID):" | awk '{print $2}') )
 if [[ ${#info[@]} -eq 0 ]]; then
-    echo "offline"
-    exit 1
+  echo "offline"
+  exit 1
 fi
 
 # cut out a needed information from the info
@@ -101,30 +101,30 @@ ssid="${info[3]}"   # wifi ssid name
 signal=""
 for ((j = 0; j < "${#signals[@]}"; j++))
 do
-    # reference of strength (rssi)
-    #  -20　Excellent
-    #  -30　Excellent
-    #  -40　Excellent
-    #  -50　Excellent
-    #  -60　better
-    #  -70　good
-    #  -80　not good
-    #  -90　bad
-    # -100　bad
-    if ((  $j == 0 && $rssi > -100 )) ||
-        (( $j == 1 && $rssi > -80  )) ||
-        (( $j == 2 && $rssi > -50  )); then
-        # make signal
-        signal="${signal}${signals[$j]} "
-    else
-        signal="${signal}  "
-    fi
+  # reference of strength (rssi)
+  #  -20　Excellent
+  #  -30　Excellent
+  #  -40　Excellent
+  #  -50　Excellent
+  #  -60　better
+  #  -70　good
+  #  -80　not good
+  #  -90　bad
+  # -100　bad
+  if ((  $j == 0 && $rssi > -100 )) ||
+    (( $j == 1 && $rssi > -80  )) ||
+    (( $j == 2 && $rssi > -50  )); then
+    # make signal
+    signal="${signal}${signals[$j]} "
+  else
+    signal="${signal}  "
+  fi
 done
 
 # If the wifi rate (wifi bandwidth) is unavailable,
 if [ "$rate" = 0 ]; then
-    echo "no_wifi"
-    exit 1
+  echo "no_wifi"
+  exit 1
 fi
 
 # Outputs wifi
